name: taco
channels:
  - conda-forge
  - defaults
dependencies:
  # - argparse # native in python > 2.7
  - emcee
  - lightkurve
  - loguru
  - numpy
  - pandas
  - python=3.8
  - r-argparser
  - r-ifultools
  - r-lomb
  - r-modelr
  - r-numderiv
  - r-tidyverse
  - scikit-learn
  - scipy
